// src/app/layout.js
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import { ProductsProvider } from "./context/ProductsContext";

// استخدام Google Fonts الصحيحة
const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Oswald({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mahmoud Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProductsProvider>{children}</ProductsProvider>
      </body>
    </html>
  );
}
